#!/usr/bin/env python3
# Copyright (c) 2026 FoBE Studio
# SPDX-License-Identifier: Apache-2.0

"""Generate a compact ZUI predictive 12-key dictionary C source."""

from __future__ import annotations

import argparse
import collections
import re
from pathlib import Path


KEYS = {
    "a": "2",
    "b": "2",
    "c": "2",
    "d": "3",
    "e": "3",
    "f": "3",
    "g": "4",
    "h": "4",
    "i": "4",
    "j": "5",
    "k": "5",
    "l": "5",
    "m": "6",
    "n": "6",
    "o": "6",
    "p": "7",
    "q": "7",
    "r": "7",
    "s": "7",
    "t": "8",
    "u": "8",
    "v": "8",
    "w": "9",
    "x": "9",
    "y": "9",
    "z": "9",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--budget", required=True, type=int)
    parser.add_argument("--max-candidates", required=True, type=int)
    parser.add_argument("--max-word-len", default=10, type=int)
    parser.add_argument("--source-note", default="")
    parser.add_argument("--source-license", default="")
    return parser.parse_args()


def word_sequence(word: str) -> str:
    return "".join(KEYS[ch] for ch in word)


def encode_sequence(sequence: str) -> int:
    code = 1
    for ch in sequence:
        code = (code << 3) | (ord(ch) - ord("2"))
    return code


def parse_words(path: Path, max_word_len: int) -> list[tuple[str, int]]:
    words: dict[str, int] = {}

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        parts = re.split(r"[\s,]+", line)
        word = parts[0].lower()
        if not re.fullmatch(r"[a-z]+", word):
            continue
        if len(word) > max_word_len:
            continue

        frequency = 1
        if len(parts) > 1:
            try:
                frequency = int(parts[1])
            except ValueError:
                frequency = 1
        if frequency <= 0:
            continue

        words[word] = max(words.get(word, 0), frequency)

    return sorted(words.items(), key=lambda item: (-item[1], item[0]))


def select_words(
    ranked_words: list[tuple[str, int]], budget: int, max_candidates: int
) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = collections.OrderedDict()
    selected_words: set[str] = set()
    selected_size = 4

    for word, _frequency in ranked_words:
        if word in selected_words:
            continue

        sequence = word_sequence(word)
        candidates = groups.get(sequence)
        new_sequence = candidates is None
        if candidates is None:
            candidates = []
        if len(candidates) >= max_candidates:
            continue

        added_size = len(word) + 1
        if new_sequence:
            added_size += 8
        if selected_size + added_size > budget:
            continue

        if new_sequence:
            groups[sequence] = candidates
        candidates.append(word)
        selected_words.add(word)
        selected_size += added_size

    return {
        sequence: candidates
        for sequence, candidates in sorted(
            groups.items(), key=lambda item: (len(item[0]), encode_sequence(item[0]))
        )
        if candidates
    }


def c_string(data: str) -> str:
    return '"' + data.replace("\\", "\\\\").replace('"', '\\"').replace("\0", "\\0") + '"'


def write_source(
    output: Path,
    groups: dict[str, list[str]],
    source_note: str,
    source_license: str,
) -> None:
    candidate_blob_parts: list[str] = []
    keys: list[int] = []
    candidate_starts: list[int] = []
    next_offset = 0

    for sequence, candidates in groups.items():
        keys.append(encode_sequence(sequence))
        candidate_starts.append(next_offset)
        for word in candidates:
            candidate_blob_parts.append(word)
            next_offset += len(word) + 1
    candidate_starts.append(next_offset)

    candidate_blob = "\0".join(candidate_blob_parts) + ("\0" if candidate_blob_parts else "")
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as fp:
        fp.write("/*\n")
        fp.write(" * Generated by scripts/zui/gen_predictive_dict.py\n")
        if source_note:
            fp.write(f" * Source: {source_note}\n")
        if source_license:
            fp.write(f" * Source-License: {source_license}\n")
        # REUSE-IgnoreStart
        fp.write(" * SPDX-License-Identifier: Apache-2.0\n")
        # REUSE-IgnoreEnd
        fp.write(" */\n\n")
        fp.write('#include "zui_predictive_internal.h"\n\n')
        fp.write(
            f"const char zui_predictive_dict_candidate_blob[] = {c_string(candidate_blob)};\n\n"
        )
        fp.write("const uint32_t zui_predictive_dict_keys[] = {\n")
        if keys:
            for key in keys:
                fp.write(f"\t{key}U,\n")
        else:
            fp.write("\t0U,\n")
        fp.write("};\n\n")
        fp.write("const uint32_t zui_predictive_dict_candidate_starts[] = {\n")
        if candidate_starts:
            for start in candidate_starts:
                fp.write(f"\t{start}U,\n")
        else:
            fp.write("\t0U,\n")
        fp.write("};\n\n")
        fp.write(f"const size_t zui_predictive_dict_entry_count = {len(keys)}U;\n")


def main() -> None:
    args = parse_args()
    ranked_words = parse_words(args.input, args.max_word_len)
    groups = select_words(ranked_words, args.budget, args.max_candidates)
    write_source(args.output, groups, args.source_note, args.source_license)


if __name__ == "__main__":
    main()
